# Generated by Django 5.0.3 on 2024-05-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord_admin', '0004_vendeurprofile_delete_clientform_alter_sale_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendeurprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='vendeurprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
