# Generated by Django 5.0.3 on 2024-05-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord_admin', '0005_remove_vendeurprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_images'),
        ),
    ]
