# Generated by Django 5.0.3 on 2024-05-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord_admin', '0006_vendeur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
