# Generated by Django 5.0.3 on 2024-05-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord_admin', '0008_rename_id_vendeur_idvendeur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendeur',
            old_name='idVendeur',
            new_name='id_Vendeur',
        ),
    ]
