# Generated by Django 5.0.3 on 2024-05-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord_admin', '0009_rename_idvendeur_vendeur_id_vendeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
            ],
        ),
    ]
