# Generated by Django 5.0.3 on 2024-05-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord_admin', '0010_mydate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyDate',
        ),
    ]
